<a href="https://colab.research.google.com/github/rondan100/Tensorflow/blob/master/segmentos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Módulo tf.math

In [2]:
import tensorflow as tf

Inserindo uma matrix

In [3]:
c = tf.constant([[1,2,3,4], [-1,-2,-3,-4], [5,6,7,8]])
print(c)

tf.Tensor(
[[ 1  2  3  4]
 [-1 -2 -3 -4]
 [ 5  6  7  8]], shape=(3, 4), dtype=int32)


In [4]:
tf.math.segment_sum(c, tf.constant([0, 0, 1]))

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [5, 6, 7, 8]], dtype=int32)>

In [9]:
tf.math.unsorted_segment_sum(c, tf.constant([0, 1, 0]), num_segments=2)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 6,  8, 10, 12],
       [-1, -2, -3, -4]], dtype=int32)>